[tool.poetry]
name = "sbyc-course-app"
version = "0.1.0"
description = "A race course map lookup web app for SBYC Friday Night Series"
authors = ["Nick Fournier <nichfournier@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gpxpy = "^1.6.2"
PyYAML = "^6.0.1"
folium = "^0.16.0"
django-crispy-forms = "^2.1"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
